const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),zlib=require('zlib');
const ROOT=__dirname, PORT=process.env.PORT||3000, ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'', SESSION_SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
const GITHUB_TOKEN=process.env.GITHUB_TOKEN||'', GITHUB_REPO=process.env.GITHUB_REPO||'', TMDB_TOKEN=process.env.TMDB_TOKEN||'', OVERRIDES_PATH='data/overrides.json';
let catalog=null, overrides={upserts:{},deleted:[],pages:[],contacts:[]}, sha=null;
const UPSTREAM=process.env.CATALOG_URL||'https://zovex.duckdns.org/movies.json';
const TMDB_CRED=String(TMDB_TOKEN||'').trim().replace(/^['\"]|['\"]$/g,'');
async function tmdb(endpoint){if(!TMDB_CRED)return null;let bearer=TMDB_CRED.length>40, sep=endpoint.includes('?')?'&':'?';let r=await fetch('https://api.themoviedb.org/3'+endpoint+(bearer?'':sep+'api_key='+encodeURIComponent(TMDB_CRED)),{headers:bearer?{authorization:'Bearer '+TMDB_CRED}:{}});return r.ok?r.json():null}
async function tmdbTitle(id){for(let kind of ['movie','tv']){let d=await tmdb(`/${kind}/${id}?language=he-IL&append_to_response=credits,videos`);if(d&&d.id)return {kind,data:d}}return null}
function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(b)}
function body(req){return new Promise((ok,no)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n>2e6){no(Error('too large'));req.destroy()}else a.push(c)});req.on('end',()=>{try{ok(JSON.parse(Buffer.concat(a).toString()||'{}'))}catch(e){no(e)}})})}
function safeEq(a,b){a=Buffer.from(String(a));b=Buffer.from(String(b));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function sign(v){return crypto.createHmac('sha256',SESSION_SECRET).update(v).digest('base64url')}
function auth(req){let m=(req.headers.cookie||'').match(/zf_session=([^;]+)/);if(!m)return false;let [v,s]=decodeURIComponent(m[1]).split('.');return +v>Date.now()&&safeEq(sign(v),s)}
function csrf(req){return req.headers['x-zf-csrf']===sign('csrf')}
async function gh(method,payload){if(!GITHUB_TOKEN||!GITHUB_REPO)return null;let r=await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${OVERRIDES_PATH}`,{method,headers:{authorization:`Bearer ${GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'zovex-flow'},body:payload&&JSON.stringify(payload)});if(r.status===404)return null;if(!r.ok)throw Error(`GitHub ${r.status}: ${await r.text()}`);return r.json()}
async function loadOverrides(){try{let d=await gh('GET');if(d){sha=d.sha;overrides=JSON.parse(Buffer.from(d.content.replace(/\n/g,''),'base64').toString())}}catch(e){console.error('override load',e.message)}}
async function saveOverrides(){let content=Buffer.from(JSON.stringify(overrides,null,2)).toString('base64'),p={message:'Update Ariel Movies catalog',content,branch:'main'};if(sha)p.sha=sha;let d=await gh('PUT',p);if(d)sha=d.content.sha;else fs.writeFileSync(path.join(ROOT,'data-overrides.local.json'),JSON.stringify(overrides,null,2))}
function merged(){catalog||(catalog=[]);let del=new Set(overrides.deleted||[]),ups=overrides.upserts||{};return catalog.filter(x=>!del.has(x.id)).map(x=>ups[x.id]?{...x,...ups[x.id]}:x).concat(Object.values(ups).filter(x=>!catalog.some(y=>y.id===x.id)))}
function file(res,p){if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end('Not found')}let ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg'};let raw=fs.readFileSync(p),h={'content-type':types[ext]||'application/octet-stream','cache-control':ext==='.json'?'no-cache':'public, max-age=300'};if(raw.length>1024&&/gzip/.test(arguments[2]||'')){raw=zlib.gzipSync(raw);h['content-encoding']='gzip'}res.writeHead(200,h);res.end(raw)}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://x'),p=u.pathname;
 if(p==='/api/admin/login'&&req.method==='POST'){let d=await body(req);if(!ADMIN_PASSWORD||!safeEq(d.password,ADMIN_PASSWORD))return json(res,401,{error:'סיסמה שגויה'});let exp=Date.now()+12*3600e3;res.setHeader('set-cookie',`zf_session=${encodeURIComponent(exp+'.'+sign(String(exp)))}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`);return json(res,200,{ok:true,csrf:sign('csrf')})}
 if(p==='/api/admin/status')return json(res,auth(req)?200:401,auth(req)?{ok:true,csrf:sign('csrf'),storage:GITHUB_TOKEN&&GITHUB_REPO?'github':'local',repo:GITHUB_REPO}:{error:'unauthorized'});
 if(p==='/api/admin/items'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'unauthorized'});let q=(u.searchParams.get('q')||'').toLowerCase(),items=merged().filter(x=>!q||[x.title,x.series_name,x.category].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,200);return json(res,200,{items,pages:overrides.pages||[]})}
 if(p.startsWith('/api/admin/item')&&['POST','DELETE'].includes(req.method)){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);if(req.method==='DELETE'){overrides.deleted=[...new Set([...(overrides.deleted||[]),d.id])];delete overrides.upserts[d.id]}else{let x=d.item||{};if(!x.id)x.id=crypto.randomUUID();overrides.upserts[x.id]=x;overrides.deleted=(overrides.deleted||[]).filter(id=>id!==x.id)}await saveOverrides();return json(res,200,{ok:true,id:d.item&&d.item.id})}
 if(p==='/api/admin/pages'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);overrides.pages=Array.isArray(d.pages)?d.pages:[];await saveOverrides();return json(res,200,{ok:true})}
 if(p.startsWith('/api/tmdb/cast/')){let id=p.split('/').pop(),r=/^\d+$/.test(id)&&await tmdbTitle(id);return json(res,r?200:404,{cast:(r&&r.data.credits&&r.data.credits.cast||[]).slice(0,18).map(x=>({id:x.id,name:x.name,character:x.character,profile:x.profile_path?`https://image.tmdb.org/t/p/w185${x.profile_path}`:null}))})}
 if(p.startsWith('/api/tmdb/title/')){let id=p.split('/').pop(),r=/^\d+$/.test(id)&&await tmdbTitle(id);if(!r)return json(res,404,{error:'not found'});let d=r.data,vids=(d.videos&&d.videos.results||[]);if(!vids.length){let vd=await tmdb(`/${r.kind}/${id}/videos?language=en-US`);vids=vd&&vd.results||[]}let v=vids.find(x=>x.site==='YouTube'&&x.type==='Trailer')||vids.find(x=>x.site==='YouTube');return json(res,200,{id:d.id,kind:r.kind,title:d.title||d.name,overview:d.overview,rating:d.vote_average,genres:(d.genres||[]).map(x=>x.name),year:String(d.release_date||d.first_air_date||'').slice(0,4),runtime:d.runtime||(d.episode_run_time||[])[0],trailer:v&&v.key,cast:(d.credits&&d.credits.cast||[]).slice(0,18).map(x=>({id:x.id,name:x.name,character:x.character,profile:x.profile_path?`https://image.tmdb.org/t/p/w185${x.profile_path}`:null}))})}
 if(p.startsWith('/api/tmdb/person/')){let id=p.split('/').pop(),d=/^\d+$/.test(id)&&await tmdb(`/person/${id}?language=he-IL&append_to_response=combined_credits`);if(!d)return json(res,404,{error:'not found'});return json(res,200,{id:d.id,name:d.name,biography:d.biography,profile:d.profile_path?`https://image.tmdb.org/t/p/w342${d.profile_path}`:null,knownFor:d.known_for_department,credits:[...new Set((d.combined_credits&&d.combined_credits.cast||[]).map(x=>x.id))]})}
 if(p==='/api/contact'&&req.method==='POST'){let d=await body(req);if(!d.body||String(d.body).length>4000)return json(res,400,{error:'invalid'});overrides.contacts=overrides.contacts||[];overrides.contacts.unshift({id:crypto.randomUUID(),email:String(d.email||''),subject:String(d.subject||''),body:String(d.body),created_at:new Date().toISOString()});overrides.contacts=overrides.contacts.slice(0,200);await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/admin/contacts'){if(!auth(req))return json(res,401,{error:'unauthorized'});return json(res,200,{contacts:overrides.contacts||[]})}
 if(p==='/api/catalog')return json(res,200,merged());
 if(p==='/admin'||p==='/admin/')return file(res,path.join(ROOT,'admin.html'),req.headers['accept-encoding']);
 if(p==='/app'||p==='/app/')return file(res,path.join(ROOT,'app.html'),req.headers['accept-encoding']);
 if(p==='/auth-mobile'||p==='/auth-mobile/')return file(res,path.join(ROOT,'auth-mobile.html'),req.headers['accept-encoding']);
 let rel=p==='/'?'index.html':p.slice(1),target=path.normalize(path.join(ROOT,rel));if(!target.startsWith(ROOT))return json(res,403,{error:'forbidden'});return file(res,target,req.headers['accept-encoding']);
 }catch(e){console.error(e);json(res,500,{error:'שגיאת שרת'})}});
async function loadCatalog(){try{let r=await fetch(UPSTREAM);if(!r.ok)throw Error('HTTP '+r.status);catalog=await r.json();console.log('catalog',catalog.length)}catch(e){console.error('catalog load',e.message);let p=path.join(ROOT,'catalog.json');catalog=fs.existsSync(p)?JSON.parse(fs.readFileSync(p)):[]}}
server.listen(PORT,()=>console.log('Ariel Movies on',PORT)); Promise.all([loadOverrides(),loadCatalog()]);
