const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto'),zlib=require('zlib');
const ROOT=__dirname, PORT=process.env.PORT||3000, ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'', SESSION_SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
const GITHUB_TOKEN=process.env.GITHUB_TOKEN||'', GITHUB_REPO=process.env.GITHUB_REPO||'', TMDB_TOKEN=process.env.TMDB_TOKEN||'', SUBDL_API_KEY=process.env.SUBDL_API_KEY||'', OPENSUBTITLES_API_KEY=process.env.OPENSUBTITLES_API_KEY||'', OMDB_API_KEY=process.env.OMDB_API_KEY||'', OPENSUBTITLES_USER=process.env.OPENSUBTITLES_USER||'', OPENSUBTITLES_PASSWORD=process.env.OPENSUBTITLES_PASSWORD||'', OVERRIDES_PATH='data/overrides.json';
const rateBuckets=new Map();function rate(req,name,max,windowMs){let ip=String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'').split(',')[0].trim(),k=name+':'+ip,now=Date.now(),a=(rateBuckets.get(k)||[]).filter(t=>now-t<windowMs);if(a.length>=max)return false;a.push(now);rateBuckets.set(k,a);return true}
let catalog=null,kanCatalog=[], overrides={upserts:{},deleted:[],pages:[],contacts:[],assets:[],folders:[],settings:{},translations:{}}, sha=null;
const UPSTREAM=process.env.CATALOG_URL||'https://zovex.duckdns.org/movies.json';
const TMDB_CRED=String(TMDB_TOKEN||'').trim().replace(/^['\"]|['\"]$/g,'');
async function tmdb(endpoint){if(!TMDB_CRED)return null;let bearer=TMDB_CRED.length>40, sep=endpoint.includes('?')?'&':'?';let r=await fetch('https://api.themoviedb.org/3'+endpoint+(bearer?'':sep+'api_key='+encodeURIComponent(TMDB_CRED)),{headers:bearer?{authorization:'Bearer '+TMDB_CRED}:{}});return r.ok?r.json():null}
async function tmdbTitle(id){for(let kind of ['movie','tv']){let d=await tmdb(`/${kind}/${id}?language=he-IL&append_to_response=credits,videos`);if(d&&d.id)return {kind,data:d}}return null}
function json(res,status,data){const b=Buffer.from(JSON.stringify(data));res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(b)}
function body(req){return new Promise((ok,no)=>{let a=[],n=0;req.on('data',c=>{n+=c.length;if(n>2e6){no(Error('too large'));req.destroy()}else a.push(c)});req.on('end',()=>{try{ok(JSON.parse(Buffer.concat(a).toString()||'{}'))}catch(e){no(e)}})})}
function safeEq(a,b){a=Buffer.from(String(a));b=Buffer.from(String(b));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function sign(v){return crypto.createHmac('sha256',SESSION_SECRET).update(v).digest('base64url')}
let firebaseCerts={data:null,until:0};async function verifyFirebaseToken(token){let [h,p,sig]=String(token||'').split('.');if(!sig)throw Error('token');let head=JSON.parse(Buffer.from(h,'base64url')),claims=JSON.parse(Buffer.from(p,'base64url')),now=Math.floor(Date.now()/1000);if(claims.aud!=='ariel-movies'||claims.iss!=='https://securetoken.google.com/ariel-movies'||claims.exp<now||claims.iat>now+60||!claims.sub)throw Error('claims');if(!firebaseCerts.data||Date.now()>firebaseCerts.until){let r=await fetch('https://www.googleapis.com/robot/v1/metadata/x509/securetoken@system.gserviceaccount.com');if(!r.ok)throw Error('certs');firebaseCerts={data:await r.json(),until:Date.now()+3600e3}}let cert=firebaseCerts.data[head.kid];if(!cert||!crypto.verify('RSA-SHA256',Buffer.from(h+'.'+p),cert,Buffer.from(sig,'base64url')))throw Error('signature');return claims}
const userKey=crypto.createHash('sha256').update(SESSION_SECRET+':users').digest();function readUsers(){let e=overrides.privateUsers;if(!e)return[];try{let iv=Buffer.from(e.iv,'base64'),tag=Buffer.from(e.tag,'base64'),d=crypto.createDecipheriv('aes-256-gcm',userKey,iv);d.setAuthTag(tag);return JSON.parse(Buffer.concat([d.update(Buffer.from(e.data,'base64')),d.final()]))}catch{return[]}}function writeUsers(users){let iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',userKey,iv),data=Buffer.concat([c.update(JSON.stringify(users)),c.final()]);overrides.privateUsers={iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:data.toString('base64')}}


function apiKeys(v){return String(v||'').split(',').map(x=>x.trim()).filter(Boolean)}let omdbKeyIndex=0,osKeyIndex=0;
async function omdb(params){let keys=apiKeys(OMDB_API_KEY);if(!keys.length)return null;for(let n=0;n<keys.length;n++){let i=(omdbKeyIndex+n)%keys.length,u=new URL('https://www.omdbapi.com/');u.searchParams.set('apikey',keys[i]);Object.entries(params).forEach(([k,v])=>v!=null&&u.searchParams.set(k,v));let r=await fetch(u,{signal:AbortSignal.timeout(10000)}),d=await r.json().catch(()=>({}));if(r.ok&&d.Response!=='False'){omdbKeyIndex=i;return d}let msg=String(d.Error||'');if(r.status===429||/limit|quota|request limit/i.test(msg)){omdbKeyIndex=(i+1)%keys.length;continue}return null}return null}
const subtitleCache=new Map(),subtitleFiles=new Map();
function srtToVtt(s){return 'WEBVTT\n\n'+String(s).replace(/^\ufeff/,'').replace(/\r/g,'').replace(/(\d{2}:\d{2}:\d{2}),(\d{3})/g,'$1.$2')}
let osToken='',osTokenAt=0;async function opensubLogin(){if(osToken&&Date.now()-osTokenAt<20*3600e3)return osToken;let osKeys=apiKeys(OPENSUBTITLES_API_KEY),osKey=osKeys[osKeyIndex%Math.max(osKeys.length,1)];if(!osKey||!OPENSUBTITLES_USER||!OPENSUBTITLES_PASSWORD)return'';let r=await fetch('https://api.opensubtitles.com/api/v1/login',{method:'POST',headers:{'api-key':osKey,'content-type':'application/json','user-agent':'ArielMovies v1'},body:JSON.stringify({username:OPENSUBTITLES_USER,password:OPENSUBTITLES_PASSWORD}),signal:AbortSignal.timeout(10000)});if(!r.ok)return'';let d=await r.json();osToken=d.token||'';osTokenAt=Date.now();return osToken}async function openSubSearch(q){let keys=apiKeys(OPENSUBTITLES_API_KEY);if(!keys.length)return[];let u=new URL('https://api.opensubtitles.com/api/v1/subtitles');u.searchParams.set('tmdb_id',q.tmdb_id);u.searchParams.set('languages',(q.languages||'he,ar,en').replace('he','he'));if(q.season)u.searchParams.set('season_number',q.season);if(q.episode)u.searchParams.set('episode_number',q.episode);let r,d;for(let n=0;n<keys.length;n++){let i=(osKeyIndex+n)%keys.length;r=await fetch(u,{headers:{'api-key':keys[i],'user-agent':'ArielMovies v1'},signal:AbortSignal.timeout(10000)});d=await r.json().catch(()=>({}));if(r.ok){osKeyIndex=i;break}if(r.status===429||r.status===403){osKeyIndex=(i+1)%keys.length;continue}throw Error('OpenSubtitles '+r.status)}if(!r?.ok)throw Error('OpenSubtitles quota');return(d.data||[]).slice(0,10).map(x=>({provider:'opensubtitles',language:x.attributes?.language,release:x.attributes?.release||'',file_id:x.attributes?.files?.[0]?.file_id}))}async function subdlSearch(q){if(!SUBDL_API_KEY)return[];let u=new URL('https://api.subdl.com/api/v1/subtitles');u.searchParams.set('api_key',SUBDL_API_KEY);u.searchParams.set('tmdb_id',q.tmdb_id);u.searchParams.set('languages',q.languages||'HE,AR,EN');if(q.season)u.searchParams.set('season_number',q.season);if(q.episode)u.searchParams.set('episode_number',q.episode);let r=await fetch(u,{signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('SubDL '+r.status);let d=await r.json();return(d.subtitles||[]).slice(0,15).map(x=>({provider:'subdl',language:x.language||x.lang,release:x.release_name||'',download:x.url||x.download_url}))}
async function zipFirstText(b){if(b.readUInt32LE(0)!==0x04034b50)throw Error('zip');let method=b.readUInt16LE(8),nameLen=b.readUInt16LE(26),extraLen=b.readUInt16LE(28),size=b.readUInt32LE(18),start=30+nameLen+extraLen,data=b.subarray(start,start+size);if(method===0)return data;if(method===8)return zlib.inflateRawSync(data);throw Error('zip method')}
async function subtitleSearch(q){let key=JSON.stringify(q),c=subtitleCache.get(key);if(c&&Date.now()-c.at<21600000)return c.data;let data=[];try{data=await subdlSearch(q)}catch(e){console.error('SubDL search',e.message)}if(!data.length)try{data=await openSubSearch(q)}catch(e){console.error('OpenSubtitles search',e.message)};subtitleCache.set(key,{at:Date.now(),data});return data}
function auth(req){let m=(req.headers.cookie||'').match(/zf_session=([^;]+)/);if(!m)return false;let [v,s]=decodeURIComponent(m[1]).split('.');return +v>Date.now()&&safeEq(sign(v),s)}
function csrf(req){return req.headers['x-zf-csrf']===sign('csrf')}
async function gh(method,payload){if(!GITHUB_TOKEN||!GITHUB_REPO)return null;let r=await fetch(`https://api.github.com/repos/${GITHUB_REPO}/contents/${OVERRIDES_PATH}`,{method,headers:{authorization:`Bearer ${GITHUB_TOKEN}`,accept:'application/vnd.github+json','content-type':'application/json','user-agent':'zovex-flow'},body:payload&&JSON.stringify(payload)});if(r.status===404)return null;if(!r.ok)throw Error(`GitHub ${r.status}: ${await r.text()}`);return r.json()}
async function loadOverrides(){try{let d=await gh('GET');if(d){sha=d.sha;overrides=JSON.parse(Buffer.from(d.content.replace(/\n/g,''),'base64').toString())}}catch(e){console.error('override load',e.message)}}
async function saveOverrides(){let content=Buffer.from(JSON.stringify(overrides,null,2)).toString('base64'),p={message:'Update Ariel Movies catalog',content,branch:'main'};if(sha)p.sha=sha;let d=await gh('PUT',p);if(d)sha=d.content.sha;else fs.writeFileSync(path.join(ROOT,'data-overrides.local.json'),JSON.stringify(overrides,null,2))}
function merged(){catalog||(catalog=[]);let base=catalog.concat(kanCatalog.filter(k=>!catalog.some(x=>x.id===k.id)));catalog=base;let del=new Set(overrides.deleted||[]),ups=overrides.upserts||{};return catalog.filter(x=>!del.has(x.id)).map(x=>ups[x.id]?{...x,...ups[x.id]}:x).concat(Object.values(ups).filter(x=>!catalog.some(y=>y.id===x.id)))}
function file(res,p){if(!fs.existsSync(p)||!fs.statSync(p).isFile()){res.writeHead(404);return res.end('Not found')}let ext=path.extname(p),types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg'};let raw=fs.readFileSync(p),h={'content-type':types[ext]||'application/octet-stream','cache-control':ext==='.json'?'no-cache':'public, max-age=300'};if(raw.length>1024&&/gzip/.test(arguments[2]||'')){raw=zlib.gzipSync(raw);h['content-encoding']='gzip'}res.writeHead(200,h);res.end(raw)}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://x'),p=u.pathname;
 if(overrides.settings&&overrides.settings.maintenance&&!auth(req)&&!p.startsWith('/admin')&&!p.startsWith('/api/admin')&&p!=='/logo.png'){if(p.startsWith('/api/'))return json(res,503,{error:'maintenance'});res.writeHead(503,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','retry-after':'300'});return res.end('<!doctype html><html lang="he" dir="rtl"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Ariel Movies · תחזוקה</title><style>body{margin:0;min-height:100vh;display:grid;place-items:center;background:#071016;color:#fff;font-family:Arial;text-align:center}.box{padding:32px}.logo{width:96px;border-radius:20px;background:#fff}h1{font-size:32px}p{color:#9db0ba}</style><div class="box"><img class="logo" src="/logo.png"><h1>האתר בתחזוקה</h1><p>אנחנו מסדרים כמה דברים. נחזור בקרוב 🍿</p></div></html>')}
 if(p==='/api/site-config')return json(res,200,{siteTitle:overrides.settings?.siteTitle||'Ariel Movies 🍿',accent:overrides.settings?.accent||'#36d6ad',defaultLang:overrides.settings?.defaultLang||'עברית'});
 if(p==='/api/admin/login'&&req.method==='POST'){let d=await body(req);if(!ADMIN_PASSWORD||!safeEq(d.password,ADMIN_PASSWORD))return json(res,401,{error:'סיסמה שגויה'});let exp=Date.now()+12*3600e3;res.setHeader('set-cookie',`zf_session=${encodeURIComponent(exp+'.'+sign(String(exp)))}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`);return json(res,200,{ok:true,csrf:sign('csrf')})}
 if(p==='/api/subtitles/search'){if(!rate(req,'subtitles',60,3600000))return json(res,429,{error:'rate limit'});let q={tmdb_id:u.searchParams.get('tmdb_id'),season:u.searchParams.get('season'),episode:u.searchParams.get('episode'),languages:u.searchParams.get('languages')};if(!/^\d+$/.test(q.tmdb_id||''))return json(res,400,{error:'tmdb_id'});let rows=await subtitleSearch(q);return json(res,200,{subtitles:rows.map((x,i)=>({url:'/api/subtitles/file?key='+encodeURIComponent(Buffer.from(JSON.stringify({...q,i})).toString('base64url')),label:(x.language||'כתוביות')+(x.release?' · '+x.release:''),lang:x.language||'he'}))})}
 if(p==='/api/subtitles/file'){if(!rate(req,'subtitle-file',30,3600000))return json(res,429,{error:'rate limit'});let q;try{q=JSON.parse(Buffer.from(u.searchParams.get('key')||'','base64url'))}catch{return json(res,400,{error:'key'})}let rows=await subtitleSearch(q),x=rows[q.i];if(!x||!x.download)return json(res,404,{error:'not found'});let ck=x.download||('os:'+x.file_id),c=subtitleFiles.get(ck);if(!c){let download=x.download;if(x.provider==='opensubtitles'){let token=await opensubLogin(),r=await fetch('https://api.opensubtitles.com/api/v1/download',{method:'POST',headers:{'api-key':OPENSUBTITLES_API_KEY,'content-type':'application/json','user-agent':'ArielMovies v1',...(token?{authorization:'Bearer '+token}:{})},body:JSON.stringify({file_id:x.file_id}),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('OpenSubtitles download '+r.status);download=(await r.json()).link}let r=await fetch(new URL(download,'https://dl.subdl.com').href,{signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('subtitle '+r.status);let b=Buffer.from(await r.arrayBuffer());if(b.length>2e6)return json(res,413,{error:'too large'});if(b[0]===0x50&&b[1]===0x4b)b=await zipFirstText(b);c=srtToVtt(b.toString('utf8'));subtitleFiles.set(ck,c)}res.writeHead(200,{'content-type':'text/vtt; charset=utf-8','cache-control':'public,max-age=86400','access-control-allow-origin':'self'});return res.end(c)}
 if(p==='/api/user/presence'&&req.method==='POST'){if(!rate(req,'presence',20,3600000))return json(res,429,{error:'rate limit'});try{let claims=await verifyFirebaseToken((req.headers.authorization||'').replace(/^Bearer\s+/i,'')),users=readUsers(),now=new Date().toISOString(),i=users.findIndex(x=>x.uid===claims.sub),entry={uid:claims.sub,name:String(claims.name||''),email:String(claims.email||''),provider:(claims.firebase&&claims.firebase.sign_in_provider)||'unknown',joinedAt:i>=0?users[i].joinedAt:now,lastActive:now};i>=0?users[i]=entry:users.push(entry);writeUsers(users);await saveOverrides();return json(res,200,{ok:true})}catch(e){return json(res,401,{error:'unauthorized'})}}
 if(p==='/api/admin/users'){if(!auth(req))return json(res,401,{error:'unauthorized'});return json(res,200,{users:readUsers()})}
 if(p==='/api/admin/status')return json(res,auth(req)?200:401,auth(req)?{ok:true,csrf:sign('csrf'),storage:GITHUB_TOKEN&&GITHUB_REPO?'github':'local',repo:GITHUB_REPO}:{error:'unauthorized'});

 if(p==='/api/admin/dashboard'){if(!auth(req))return json(res,401,{error:'unauthorized'});let a=merged(),cats={};a.forEach(x=>cats[x.category||'אחר']=(cats[x.category||'אחר']||0)+1);return json(res,200,{total:a.length,movies:a.filter(x=>!x.series_name).length,episodes:a.filter(x=>x.series_name).length,categories:Object.entries(cats).sort((a,b)=>b[1]-a[1]),missingVideo:a.filter(x=>!x.video_url&&!x.video_id).length,missingPoster:a.filter(x=>!x.thumbnail_url).length,contacts:(overrides.contacts||[]).length,users:readUsers().length,custom:Object.keys(overrides.upserts||{}).length,deleted:(overrides.deleted||[]).length,assets:overrides.assets||[],folders:overrides.folders||[],settings:overrides.settings||{}})}
 if(p==='/api/admin/bulk'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req),ids=new Set(d.ids||[]);if(d.action==='delete'){overrides.deleted=[...new Set([...(overrides.deleted||[]),...ids])];ids.forEach(id=>delete overrides.upserts[id])}else if(d.action==='category'){merged().filter(x=>ids.has(x.id)).forEach(x=>overrides.upserts[x.id]={...x,category:d.value})}await saveOverrides();return json(res,200,{ok:true,count:ids.size})}
 if(p==='/api/admin/import'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req),rows=Array.isArray(d.items)?d.items:[];rows.slice(0,500).forEach(x=>{if(!x.id)x.id=crypto.randomUUID();if(x.title)overrides.upserts[x.id]=x});await saveOverrides();return json(res,200,{ok:true,count:Math.min(rows.length,500)})}
 if(p==='/api/admin/settings'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);overrides.settings={...(overrides.settings||{}),...(d.settings||{})};await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/admin/folders'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req),name=String(d.name||'').trim().replace(/[\/]/g,'-');if(!name)return json(res,400,{error:'name'});overrides.folders=overrides.folders||[];if(!overrides.folders.includes(name))overrides.folders.push(name);await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/admin/folders'&&req.method==='DELETE'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req),name=String(d.name||'');overrides.folders=(overrides.folders||[]).filter(x=>x!==name);(overrides.assets||[]).forEach(x=>{if(x.folder===name)x.folder=''});await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/admin/assets'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req),name=String(d.name||'file').replace(/[^\w.()א-ת -]/g,'-'),folder=String(d.folder||'').replace(/[\/]/g,'-'),data=String(d.data||'');if(!data.startsWith('data:')||data.length>1400000)return json(res,400,{error:'קובץ עד 1MB'});let id=crypto.randomUUID();overrides.assets=overrides.assets||[];overrides.assets.unshift({id,name,folder,data,created_at:new Date().toISOString()});await saveOverrides();return json(res,200,{ok:true,id})}
 if(p==='/api/admin/assets'&&req.method==='DELETE'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);overrides.assets=(overrides.assets||[]).filter(x=>x.id!==d.id);await saveOverrides();return json(res,200,{ok:true})}
 if(p.startsWith('/asset/')){let id=p.split('/').pop(),x=(overrides.assets||[]).find(a=>a.id===id);if(!x)return json(res,404,{error:'not found'});let m=x.data.match(/^data:([^;]+);base64,(.+)$/);if(!m)return json(res,404,{error:'bad asset'});let b=Buffer.from(m[2],'base64');res.writeHead(200,{'content-type':m[1],'content-disposition':`inline; filename*=UTF-8''${encodeURIComponent(x.name)}`,'cache-control':'public,max-age=3600'});return res.end(b)}
 if(p==='/api/admin/items'&&req.method==='GET'){if(!auth(req))return json(res,401,{error:'unauthorized'});let q=(u.searchParams.get('q')||'').toLowerCase(),items=merged().filter(x=>!q||[x.title,x.series_name,x.category].some(v=>String(v||'').toLowerCase().includes(q))).slice(0,200);return json(res,200,{items,pages:overrides.pages||[]})}
 if(p.startsWith('/api/admin/item')&&['POST','DELETE'].includes(req.method)){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);if(req.method==='DELETE'){overrides.deleted=[...new Set([...(overrides.deleted||[]),d.id])];delete overrides.upserts[d.id]}else{let x=d.item||{};if(!x.id)x.id=crypto.randomUUID();overrides.upserts[x.id]=x;overrides.deleted=(overrides.deleted||[]).filter(id=>id!==x.id)}await saveOverrides();return json(res,200,{ok:true,id:d.item&&d.item.id})}
 if(p==='/api/admin/pages'&&req.method==='POST'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);overrides.pages=Array.isArray(d.pages)?d.pages:[];await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/localize-batch'&&req.method==='POST'){if(!rate(req,'localize',30,60000))return json(res,429,{error:'rate limit'});let d=await body(req),lang=['en','ar'].includes(d.lang)?d.lang:'en',ids=[...new Set((d.ids||[]).map(String))].slice(0,12),changed=false,results={};overrides.translations=overrides.translations||{};for(let id of ids){let ck=id+':'+lang;if(overrides.translations[ck]){results[id]=overrides.translations[ck];continue}let x=merged().find(x=>String(x.id||x.custom_slug)===id);if(!x)continue;let td=null;if(x.tmdb_id){for(let k of ['movie','tv']){let q=await tmdb(`/${k}/${x.tmdb_id}?language=${lang}`);if(q&&q.id){td=q;break}}}if(!td){let title=x.en_title||x.series_name||x.title,year=String(x.year||'').slice(0,4);for(let k of ['movie','tv']){let q=await tmdb(`/search/${k}?language=${lang}&query=${encodeURIComponent(title)}${year?'&year='+year:''}`),r=q&&q.results&&q.results[0];if(r&&(!year||String(r.release_date||r.first_air_date||'').startsWith(year))){td=r;break}}}let out={title:td&&(td.title||td.name)||null,overview:td&&td.overview||null,tmdb_id:td&&td.id||x.tmdb_id||null,lang,matched:!!td};overrides.translations[ck]=out;results[id]=out;changed=true}if(changed)await saveOverrides();return json(res,200,{results})}
 if(p==='/api/localize'&&req.method==='POST'){if(!rate(req,'localize',30,60000))return json(res,429,{error:'rate limit'});let d=await body(req),id=String(d.id||''),lang=['en','ar'].includes(d.lang)?d.lang:'en',x=merged().find(x=>String(x.id||x.custom_slug)===id);if(!x)return json(res,404,{error:'not found'});overrides.translations=overrides.translations||{};let ck=id+':'+lang;if(overrides.translations[ck])return json(res,200,overrides.translations[ck]);let kind=null,td=null;if(x.tmdb_id){for(let k of ['movie','tv']){let q=await tmdb(`/${k}/${x.tmdb_id}?language=${lang}`);if(q&&q.id){kind=k;td=q;break}}}if(!td){let title=x.en_title||x.series_name||x.title,year=String(x.year||'').slice(0,4);for(let k of ['movie','tv']){let q=await tmdb(`/search/${k}?language=${lang}&query=${encodeURIComponent(title)}${year?'&year='+year:''}`),r=q&&q.results&&q.results[0];if(r&&(!year||String(r.release_date||r.first_air_date||'').startsWith(year))){kind=k;td=r;break}}}let out={title:td&&(td.title||td.name)||null,overview:td&&td.overview||null,tmdb_id:td&&td.id||x.tmdb_id||null,lang,matched:!!td};overrides.translations[ck]=out;await saveOverrides();return json(res,200,out)}
 if(p==='/api/omdb/title'){if(!rate(req,'omdb',60,3600000))return json(res,429,{error:'rate limit'});let d=await omdb({i:u.searchParams.get('imdb_id'),t:u.searchParams.get('title'),y:u.searchParams.get('year'),plot:'full'});return json(res,d?200:404,d||{error:'not found'})}
 if(p==='/api/tmdb/ratings'){let ids=[...new Set((u.searchParams.get('ids')||'').split(',').filter(x=>/^\d+$/.test(x)))].slice(0,20),ratings={};await Promise.all(ids.map(async id=>{let r=await tmdbTitle(id);if(r)ratings[id]=r.data.vote_average||null}));return json(res,200,{ratings})}
 if(p.startsWith('/api/tmdb/cast/')){let id=p.split('/').pop(),r=/^\d+$/.test(id)&&await tmdbTitle(id);return json(res,r?200:404,{cast:(r&&r.data.credits&&r.data.credits.cast||[]).slice(0,18).map(x=>({id:x.id,name:x.name,character:x.character,profile:x.profile_path?`https://image.tmdb.org/t/p/w185${x.profile_path}`:null}))})}
 if(p.startsWith('/api/tmdb/title/')){let id=p.split('/').pop(),r=/^\d+$/.test(id)&&await tmdbTitle(id);if(!r)return json(res,404,{error:'not found'});let d=r.data,vids=(d.videos&&d.videos.results||[]);if(!vids.length){let vd=await tmdb(`/${r.kind}/${id}/videos?language=en-US`);vids=vd&&vd.results||[]}let v=vids.find(x=>x.site==='YouTube'&&x.type==='Trailer')||vids.find(x=>x.site==='YouTube');return json(res,200,{id:d.id,kind:r.kind,title:d.title||d.name,overview:d.overview,rating:d.vote_average,genres:(d.genres||[]).map(x=>x.name),year:String(d.release_date||d.first_air_date||'').slice(0,4),runtime:d.runtime||(d.episode_run_time||[])[0],trailer:v&&v.key,cast:(d.credits&&d.credits.cast||[]).slice(0,18).map(x=>({id:x.id,name:x.name,character:x.character,profile:x.profile_path?`https://image.tmdb.org/t/p/w185${x.profile_path}`:null}))})}
 if(p.startsWith('/api/tmdb/person/')){let id=p.split('/').pop(),d=/^\d+$/.test(id)&&await tmdb(`/person/${id}?language=he-IL&append_to_response=combined_credits`);if(!d)return json(res,404,{error:'not found'});return json(res,200,{id:d.id,name:d.name,biography:d.biography,profile:d.profile_path?`https://image.tmdb.org/t/p/w342${d.profile_path}`:null,knownFor:d.known_for_department,credits:[...new Set((d.combined_credits&&d.combined_credits.cast||[]).map(x=>x.id))]})}
 if(p==='/api/contact'&&req.method==='POST'){if(!rate(req,'contact',5,3600000))return json(res,429,{error:'rate limit'});let d=await body(req);if(!d.body||String(d.body).length>4000)return json(res,400,{error:'invalid'});overrides.contacts=overrides.contacts||[];overrides.contacts.unshift({id:crypto.randomUUID(),email:String(d.email||''),subject:String(d.subject||''),body:String(d.body),created_at:new Date().toISOString()});overrides.contacts=overrides.contacts.slice(0,200);await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/admin/contacts'&&req.method==='DELETE'){if(!auth(req)||!csrf(req))return json(res,403,{error:'forbidden'});let d=await body(req);overrides.contacts=(overrides.contacts||[]).filter(x=>x.id!==d.id);await saveOverrides();return json(res,200,{ok:true})}
 if(p==='/api/admin/contacts'){if(!auth(req))return json(res,401,{error:'unauthorized'});return json(res,200,{contacts:overrides.contacts||[]})}
 if(p.startsWith('/api/play/')){let id=decodeURIComponent(p.slice('/api/play/'.length)),x=merged().find(x=>String(x.id||x.custom_slug)===id);if(!x)return json(res,404,{error:'not found'});let v=String(x.video_url||x.video_id||x.youtube_id||''),dest=v,m;if(!v)return json(res,404,{error:'no video'});if((m=v.match(/<iframe[^>]+src=["']([^"']+)/i)))dest=m[1];else if((x.type||'').toLowerCase()==='youtube'||v.includes('youtu')){let y=String(x.youtube_id||'').trim();if(!/^[\w-]{6,}$/.test(y)){m=v.match(/(?:youtu\.be\/|[?&]v=|embed\/|shorts\/|live\/)([\w-]{6,})/i);y=m&&m[1]||''}if(!y)return json(res,404,{error:'invalid youtube video'});dest='https://www.youtube-nocookie.com/embed/'+y+'?autoplay=1&playsinline=1&rel=0'}else if(((x.type||'')==='drive'||v.includes('drive.google'))&&(m=v.match(/\/d\/([^/]+)/)))dest='https://drive.google.com/file/d/'+m[1]+'/preview';res.writeHead(302,{location:dest,'cache-control':'private,no-store','referrer-policy':'no-referrer'});return res.end()}
 if(p==='/api/catalog'){let ar={};try{ar=JSON.parse(fs.readFileSync(path.join(ROOT,'ar-titles.json'),'utf8'))}catch(e){}return json(res,200,merged().map(({video_url,video_id,...x})=>{let v=ar[String(x.id||x.custom_slug)];if(v&&v.title)x.ar_title=v.title;return x}))}
 if(['/favorites','/continue','/history'].includes(p))return file(res,path.join(ROOT,'index.html'),req.headers['accept-encoding']);
 if(p==='/admin'||p==='/admin/')return file(res,path.join(ROOT,'admin.html'),req.headers['accept-encoding']);
 if(p==='/app'||p==='/app/')return file(res,path.join(ROOT,'app.html'),req.headers['accept-encoding']);
 if(p==='/auth-mobile'||p==='/auth-mobile/')return file(res,path.join(ROOT,'auth-mobile.html'),req.headers['accept-encoding']);
 let publicFiles={'/':'index.html','/index.html':'index.html','/admin.html':'admin.html','/app.html':'app.html','/auth-mobile.html':'auth-mobile.html','/logo.png':'logo.png','/manifest.json':'manifest.json','/favicon.ico':'favicon.ico','/service-worker.js':'service-worker.js'},rel=publicFiles[p];if(!rel)return json(res,404,{error:'not found'});return file(res,path.join(ROOT,rel),req.headers['accept-encoding']);
 }catch(e){console.error(e);json(res,500,{error:'שגיאת שרת'})}});
let tmdbMatching=false;
function normTitle(s){return String(s||'').normalize('NFKD').replace(/[\u0591-\u05C7]/g,'').toLowerCase().replace(/[^a-z0-9\u0590-\u05ff\u0600-\u06ff]+/g,' ').trim()}
async function autoMatchTmdb(){if(tmdbMatching||!TMDB_CRED||!catalog?.length)return;tmdbMatching=true;try{overrides.settings=overrides.settings||{};let map=overrides.settings.tmdbMatches||{},weak=overrides.settings.tmdbWeak||{},targets=new Map();catalog.filter(x=>!x.tmdb_id).forEach(x=>{let title=x.series_name||x.title,key=(x.series_name?'series:':'title:')+normTitle(title)+'|'+String(x.year||'');if(title&&!map[key]&&!weak[key])targets.set(key,{title,year:x.year,type:x.series_name?'tv':'movie'})});let arr=[...targets];for(let n=0;n<arr.length;n+=4)await Promise.all(arr.slice(n,n+4).map(async([key,x])=>{try{let q=await tmdb(`/search/${x.type}?language=he-IL&query=${encodeURIComponent(x.title)}${x.year?'&year='+x.year:''}`),r=q?.results?.[0],date=r&&(r.release_date||r.first_air_date||''),same=normTitle(r&&(r.title||r.name))===normTitle(x.title),year=!x.year||!date||String(date).startsWith(String(x.year));if(r&&same&&year)map[key]=r.id;else weak[key]={candidate:r?.id||null,name:r&&(r.title||r.name)||'',checkedAt:new Date().toISOString()}}catch(e){}}));overrides.settings.tmdbMatches=map;overrides.settings.tmdbWeak=weak;catalog.forEach(x=>{if(x.tmdb_id)return;let key=(x.series_name?'series:':'title:')+normTitle(x.series_name||x.title)+'|'+String(x.year||'');if(map[key])x.tmdb_id=map[key]});if(arr.length)await saveOverrides();console.log('tmdb auto-match',Object.keys(map).length,'matched',Object.keys(weak).length,'review')}finally{tmdbMatching=false}}
let catalogEtag='',catalogModified='',catalogRefresh=null,catalogFailures=0,catalogRetryAfter=0;
function validCatalog(x){return Array.isArray(x)&&x.length>100&&x.every(v=>v&&typeof v==='object'&&(v.id!=null||v.custom_slug)&&typeof (v.title||v.series_name)==='string')}
function loadKanCatalog(){try{let p=path.join(ROOT,'kan-youtube.json'),d=JSON.parse(fs.readFileSync(p,'utf8'));kanCatalog=validCatalog(d)?d:[];console.log('kan catalog',kanCatalog.length)}catch(e){console.error('kan catalog',e.message);kanCatalog=[]}}
async function loadCatalog(initial=false){loadKanCatalog();if(catalogRefresh)return catalogRefresh;if(!initial&&Date.now()<catalogRetryAfter)return false;catalogRefresh=(async()=>{try{let headers={};if(catalogEtag)headers['if-none-match']=catalogEtag;if(catalogModified)headers['if-modified-since']=catalogModified;let r=await fetch(UPSTREAM,{headers,signal:AbortSignal.timeout(15000)});if(r.status===304){catalogFailures=0;catalogRetryAfter=0;return true}if(!r.ok)throw Error('HTTP '+r.status);let candidate=await r.json();if(!validCatalog(candidate))throw Error('catalog validation failed');catalog=candidate;catalogEtag=r.headers.get('etag')||catalogEtag;catalogModified=r.headers.get('last-modified')||catalogModified;catalogFailures=0;catalogRetryAfter=0;console.log('catalog refreshed',catalog.length);return true}catch(e){catalogFailures++;catalogRetryAfter=Date.now()+Math.min(6*3600e3,15*60000*2**(catalogFailures-1));console.error('catalog refresh',e.message,'keeping last good');if(initial&&!catalog){let p=path.join(ROOT,'catalog.json');try{let fallback=JSON.parse(fs.readFileSync(p));catalog=validCatalog(fallback)?fallback:[]}catch{catalog=[]}}return false}finally{catalogRefresh=null}})();return catalogRefresh}
server.listen(PORT,()=>console.log('Ariel Movies on',PORT));Promise.all([loadOverrides(),loadCatalog(true)]);setInterval(()=>loadCatalog(false),60*60*1000).unref();setTimeout(autoMatchTmdb,20000);setInterval(autoMatchTmdb,24*3600*1000).unref();
